### ISSUE TITLE
EA Play is now forced, crash when booting with mods

### ISSUE THREAD

**Issue by subiesubiesubie** [505e06b2/FrostyToolsuite-Linux#4] opened 2023-06-06 01:37 UTC
Currently cannot load Need For Speed Heat with the shim, as it just leads to the runMod.cmd popping up and the game crashing. Using Frosty Mod Manager 1.0.6.2, GE-Proton 8-4 and KDE Neon 22.04.

**Comment by 505e06b2** [comment] 2023-06-10 16:46
I'm able to replicate this issue when launching with the EA App through Steam. Previously, it was possible to use the Origin Thin Client mentioned in the [troubleshooting steps](https://github.com/505e06b2/FrostyToolsuite-Linux#issues-with-ea-play-no-steam-overlay-crashes), but this seems to be a dead end now as EA have removed this functionality. It may be possible to circumvent updating to the EA App and play offline, but at that point we may as well use a crack.

I've renamed this issue and will leave it open until another way to launch is found

**Comment by 505e06b2** [comment] 2023-06-10 21:55
Through some experimentation with EA Play, the shim does seem to work if modified to not pass the `-datapath` argument to NFS. When it is passed, the game will quickly exit with a non-zero exitcode (42). Using an absolute path for this results in the same. Overriding bcrypt.dll does not affect the outcome.

Setting `-datapath` to a directory that does not exist also results in an early exit, but indicates success (0)

**Comment by subiesubiesubie** [comment] 2023-06-11 23:13
How do I modify the shim so that the `-datapath` argument isn't passed to the game?

**Comment by 505e06b2** [comment] 2023-06-11 23:52
If you want a way to play the game online without mods, but without removing the shim, change line 4 of `runMod.cmd` to just `"original_%~nx1"`. Renaming the shim/game binaries back to their originals might be preferred though

**Comment by 505e06b2** [comment] 2023-06-12 12:33
**Fix found! There seem to be regressions affecting mods in v8-\* of Proton GE**

I will alter the steps to include a more detailed fix, but the gist is:
1. Make sure to install the latest version of Proton GE 7
    - Version [v7-55](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-55) is known to work
3. Install the **Full** Version of OriginSetup-10.5.119.52718.exe ([Mirror/Archive Site](https://taskinoz.com/origin/)) into your ProtonPrefix
4. _Before you attempt to run the game_, edit the equivalent of `C:\ProgramData\Origin\local.xml` and add the following keys above the closing `</Settings>` tag ([source](https://twitter.com/p0358/status/1635796691902160896)):
```xml
<Setting value="true" key="MigrationDisabled" type="1"/>
<Setting key="UpdateURL" value="http://not.real/" type="10"/>
<Setting key="AutoPatchGlobal" value="false" type="1"/>
<Setting key="AutoUpdate" value="false" type="1"/>

I will close this issue once the readme has been updated

**Comment by subiesubiesubie** [comment] 2023-06-14 00:53
Still having issues with running, even after applying the Origin fix. The command prompt window no longer exists, but the game still fails to run for me.

**Comment by 505e06b2** [comment] 2023-06-17 20:34
> Still having issues with running, even after applying the Origin fix. The command prompt window no longer exists, but the game still fails to run for me.

Are you using Proton GE 7-55? From my testing, it seems as though any version of Proton 8 has trouble booting the game with mods

**Comment by subiesubiesubie** [comment] 2023-06-17 21:00
I am using Proton GE 7-55, if I use any version of Proton 8 it crashes with the command prompt again.

**Comment by subiesubiesubie** [comment] 2023-06-18 02:27
Finally managed to get it working, I believe it was changing the datapath to Linuxmod that helped fix it. Will try with other Proton versions and even the EA app installed to see if it would apply.

**Comment by subiesubiesubie** [comment] 2023-06-18 02:39
After testing with GE-Proton 7-39 and 7-55, the game works fine, with `/tmp/nfs.log` outputting:
[nfs.log](https://github.com/505e06b2/FrostyToolsuite-Linux/files/11780440/nfs.log)
With GE-Proton 8, the command prompt still occurs even with Origin installed, and the EA app crashes when installed if using Proton 7.*

**Comment by 505e06b2** [comment] 2023-06-18 03:14
Cool, glad to hear it's working :+1: 
Do you happen to know which version of Frosty you're using so I can put it in the readme? It should be accessible via the menubar: Help > About Frosty Editor

**Comment by subiesubiesubie** [comment] 2023-06-18 03:37
Yeah, its Frosty Mod Manager 1.0.6.2. It does occasionally crash on startup for me but the mods load fine with it

**Closed** 2023-06-18 12:51 UTC
Labels: NFS: Heat
